// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tztekzfevwelpemnfpvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6dGVremZldndlbHBlbW5mcHZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NzYzNzcsImV4cCI6MjA3MDA1MjM3N30.43Yiu1U23gqg5TAjWefdDvG-0_nO_brSB4XXlKaO_q0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});