// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxsztiaxjmqniiqdrjoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4c3p0aWF4am1xbmlpcWRyam9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMjk4MjAsImV4cCI6MjA2NTgwNTgyMH0.Ax8OjnbwnEf9E3b1F9X6pBtOX2pn91e59F8UEsWk1nk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});